typography_spectrum: 0.82
content_rating:
  adult: false
color:
  saturation: 0.4375
  brandStrength: 1
  rhythmicContrast: 0.75
  brandColors:
    - '#f3f3f3'
    - '#262626'
    - '#4e4e4e'
    - '#b6b195'
    - '#c8c8c8'
  lightness: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1403509
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac158a34-c6cd-4bc5-975f-e7115bd4bad7.png
name: Goldsborough Law
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/40b3d8c2-93c8-4707-bc16-1178394fad4d.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Goldsborough Law
description: Serving your legal needs in the Piedmont Triad
purpose: []
