name: goldsborough law
favicon: null
layout_spectrum: 0.49864
typography_spectrum: 0.82
title: Goldsborough Law
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#262626'
    - '#4e4e4e'
    - '#b6b195'
    - '#c8c8c8'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
