name: goldsborough law
favicon: null
layout_spectrum: 0.6728499
typography_spectrum: 0.62126
title: Goldsborough Law
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#545351'
    - '#ffd800'
    - '#000000'
    - '#edece6'
    - '#bfbdb5'
  brandStrength: 1
  lightness: 0.9266442
  saturation: 0.6753795
  rhythmicContrast: 0.8482293
purpose: []
