title: Goldsborough Law
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6875
  brandStrength: 1
  lightness: 0.5625
  brandColors:
    - '#FFFFFF'
    - '#CDCDCD'
    - '#32CDCD'
    - '#FE3533'
    - '#7E7E7E'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: goldsborough law
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.82
layout_spectrum: 0.6728499
